### ISSUE TITLE
The layer block is missing in generator.py

### ISSUE THREAD

**Issue by hjdw2** [IBM/gfmn#2]
I tried to reproduce the results in the paper, but there is no definition for ConvEncoderSkipConnectionBlock. 
I guess it was missing.

**Comment by ink-pad** [comment]
Hello, @hjdw2. 
I accidentally happened to land on this today and read your comment for the first time. It is pity that I didn't get to read and address your issue. I have updated the code with the latest comment. https://github.com/IBM/gfmn/commit/2cdfb13d82d1fad483fd746b29317cfae671daea
